### ISSUE TITLE
Not compiling with current build.

### ISSUE THREAD

**Issue by Ikfes** [3ndos/AnticheatModule#1]
Did in following order:

git clone https://github.com/azerothcore/azerothcore-wotlk.git azerothcore
cd azerothcore
cd modules
git clone -b master https://github.com/3ndos/AnticheatModule.git
cd ..
mkdir build; cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=/root/azeroth-server/ -DTOOLS=0 -DSCRIPTS=1
make -j 4
make install

Error:

[ 99%] Building CXX object src/scripts/CMakeFiles/scripts.dir/__/__/modules/AnticheatModule/src/PassiveAnticheat.cpp.o
[ 99%] Building CXX object src/scripts/CMakeFiles/scripts.dir/__/__/modules/AnticheatModule/src/AnticheatMgr.cpp.o
/root/azerothcore/modules/AnticheatModule/src/AnticheatMgr.cpp:19:34: fatal error: Configuration\Config.h: No such file or directory
 #include "Configuration\Config.h"
                                  ^
compilation terminated.
src/scripts/CMakeFiles/scripts.dir/build.make:12474: recipe for target 'src/scripts/CMakeFiles/scripts.dir/__/__/modules/AnticheatModule/src/AnticheatMgr.cpp.o' failed
make[2]: *** [src/scripts/CMakeFiles/scripts.dir/__/__/modules/AnticheatModule/src/AnticheatMgr.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1205: recipe for target 'src/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/scripts/CMakeFiles/scripts.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
root@Trinity:~/azerothcore/build#

**Comment by falzard** [comment]
I also tried to compile it and here is my error:
```
/azerothserver/test_azerothcore/modules/AnticheatModule/src/AnticheatMgr.cpp:19:34: fatal error: Configuration\Config.h: No such file or directory
 #include "Configuration\Config.h"
                                  ^
compilation terminated.
src/scripts/CMakeFiles/scripts.dir/build.make:12497: recipe for target 'src/scripts/CMakeFiles/scripts.dir/__/__/modules/AnticheatModule/src/AnticheatMgr.cpp.o' failed
make[2]: *** [src/scripts/CMakeFiles/scripts.dir/__/__/modules/AnticheatModule/src/AnticheatMgr.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1220: recipe for target 'src/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/scripts/CMakeFiles/scripts.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by 3ndos** [comment]
try with latest commit

**Comment by Ikfes** [comment]
Still failing but different message now.

http://pastebin.com/raw/AngETauf

**Comment by 3ndos** [comment]
try again with 650b15bdbe233ebe40cf79835decfbca1527e122

**Comment by Ikfes** [comment]
http://pastebin.com/raw/HKD8n5gA

Errors.

**Comment by 3ndos** [comment]
This is why you don't rush commits.
bd32864476088c08cf8e2e651b2466af1fccf3f4
